### ISSUE TITLE
KDE's desktop change widget doesn't any virtual desktop upon compiz startup

### ISSUE THREAD

**Issue by nice0051** [compiz-reloaded/compiz#92]
I use compiz-0.8.14 from http://download.opensuse.org/tumbleweed/repo/oss/ on a 64 bit OpenSuse TumbleWeed system with Plasma 5.11.2 desktop from KDE. It works almost perfectly with only some minor problems. One of these is that when I change to compiz window manager from kwin, then KDE's desktop change widget becomes empty. That is, it shows zero virtual desktop, so it seems to disappear from the panel. It means that I cannot change between virtual desktop using KDE's widget, only by compiz's keyboard shortcuts (eg. Alt+Ctrl+righ or Alt+Ctrl+mouse drag).

However, when I open the Desktop Size tab in the General Options module in compiz config manager (where my hsize and vsize parameters are 4 and 1 respectively) and I change my virtual desktop size, the KDE's desktop change widget immediately detects the virtual desktops, is suddenly appears on the plasma panel and starts to fuction well.

I don't know what the mechanism is behind this problem, but can you fix this bug? Alternatively, if it's a KDE bug, can you add a bugfix option for this issue in compiz?

Thank you in advance for investigating this problem.

**Comment by ethus3h** [comment]
I suspect this has to do with the difference between desktops and viewports (IIRC, Compiz uses viewports, while most other desktop pagers use desktops?) For whatever it's worth, the Plasma pager works fine for me. I'm using Plasma 5.10.5 with Git Compiz-Reloaded. What versions are you using?

**Comment by ethus3h** [comment]
Actually, now that I think about it, does this problem occur when you configure Compiz as your window manager through KDE settings, so it starts automatically with the session, bypassing KWin entirely? That's how I'm starting it, and I wonder if starting with KWin and then switching might be causing problems. (How to set this up, instructions apply to various distributions not just Arch: https://wiki.archlinux.org/index.php/KDE#Using_an_alternative_window_manager )

**Comment by nice0051** [comment]
I'm using Plasma 5.11.2. I tried to start compiz as KDE's default window manager, and it worked! The problem only occurs if I switch to compiz from kwin.

**Comment by ethus3h** [comment]
I wonder if Plasma might be detecting that KWin uses workspaces instead of viewports, and not re-detecting that on changing the window manager. They might not handle that since it's kind of an edge case. A really ugly workaround could perhaps be killing and restarting plasmashell when compiz is restarted, but that would cause other problems, I think, and certainly wouldn't be good to include by default in compiz itself (more suited to a shell script on your end IMO).

If my hypothesis is correct, I'm inclined to think that this isn't really something that can be fixed effectively from Compiz's end, rather it might be good to submit a patch to Plasma to detect and handle this change when it happens.

I have a feeling the Plasma maintainers might be disinclined to put a lot of effort in to fix this, though, since I don't think it would be that common to be switching between window managers within a single session (they've got bigger fish to fry, I think). You might have more luck if you provide them a patch, perhaps.

**Comment by nice0051** [comment]
Sadly, I'm not qualified to write that patch, but I can happily live with this issue. I only reported it to help to make the already outstanding compiz reloaded even better. My other report (https://github.com/compiz-reloaded/compiz/issues/91) might be more serious though. Thank you for the answers.

**Comment by soreau** [comment]
As far as I understand, these are kde bugs and not likely to be fixed since kde devs aren't concerned about compatibility with compiz.
